Interim commit, work in progress...

diff --git a/deploy-all b/deploy-all
--- a/deploy-all
+++ b/deploy-all
@@ -49,7 +49,8 @@ to_title() {
 
 timestamp=$(date +%s%3N)
 
-regions=(ApSoutheast2)
+# Define the order in which regions should be deployed, US is deployed first as ACM certificates are a dependency
+regions=(UsEast1 ApSoutheast2)
 
 if [[ "${parameters[0]}" == "*" ]]; then
   projects=()
@@ -81,105 +82,114 @@ for project in "${projects[@]}"; do
       mv ../Output/${project} ../Backups/${timestamp}
     fi
 
-    for region_folder in ./${project}/*; do
-      if [[ -d ${region_folder} ]]; then
-        region_folder=$(basename ${region_folder})
-        region_hyphen=$(echo ${region_folder} | sed 's/\([a-z0-9]\)\([A-Z0-9]\)/\1-\L\2/g');
-        region_hyphen=$(to_lower ${region_hyphen})
+    for region_current in "${regions[@]}"; do
+      region_current_hyphen=$(echo ${region_current} | sed 's/\([a-z0-9]\)\([A-Z0-9]\)/\1-\L\2/g');
+      region_current_hyphen=$(to_lower ${region_current_hyphen})
 
-        for environment in ./${project}/${region_folder}/*; do
-          if [[ -d ${environment} ]]; then
-            environment=$(basename ${environment})
-            if [[ ${#} < 2 || "${environments[@]}" =~ "${environment}" ]]; then
-              environment_lower=$(to_lower ${environment})
-              project_lower=$(to_lower ${project})
-              aws_account_id=$(cat ./${project}/${region_folder}/BuildManifest.json | jq -r ".Infrastructure.Environments[\"${environment}\"].AwsAccountId")
-              s3_bucket="artifacts.infrastructure-manual.${project_lower}.${environment_lower}.eonx.com"
-              s3_prefix="Infrastructure/${timestamp}"
+      for region_folder in ./${project}/*; do
+        if [[ -d ${region_folder} ]]; then
+          region_folder=$(basename ${region_folder})
+          region_hyphen=$(echo ${region_folder} | sed 's/\([a-z0-9]\)\([A-Z0-9]\)/\1-\L\2/g');
+          region_hyphen=$(to_lower ${region_hyphen})
 
-              echo
-              echo "Project:                ${project_lower}"
-              echo "Environment:            ${environment_lower}"
-              echo "AWS Account:            ${aws_account_id}"
-              echo "AWS Region:             ${region_hyphen}"
-              echo "Template Bucket:        ${s3_bucket}/${s3_prefix}"
-              echo
+          if [[ "${region_current_hyphen}" == "${region_hyphen}" ]]; then
+            for environment in ./${project}/${region_folder}/*; do
+              if [[ -d ${environment} ]]; then
+                environment=$(basename ${environment})
+                if [[ ${#} < 2 || "${environments[@]}" =~ "${environment}" ]]; then
+                  environment_lower=$(to_lower ${environment})
+                  project_hyphen=$(echo ${project} | sed 's/\([a-z0-9]\)\([A-Z0-9]\)/\1-\L\2/g');
+                  project_hyphen=$(to_lower ${project_hyphen})
+                  project_hyphen_lower=$(to_lower ${project_hyphen})
+                  project_snake=$(echo ${project_hyphen_lower} | sed 's/\([a-z0-9]\)\([A-Z0-9]\)/\1-\L\2/g');
 
-              builder \
-                --config      ./${project}/${region_folder}/BuildManifest.json \
-                --path-output ../Output/${project}/${region_folder} \
-                --environment ${environment}
+                  aws_account_id=$(cat ./${project}/${region_folder}/BuildManifest.json | jq -r ".Infrastructure.Environments[\"${environment}\"].AwsAccountId")
+                  s3_bucket="artifacts.infrastructure-manual.${project_hyphen_lower}.${environment_lower}.eonx.com"
+                  s3_prefix="Infrastructure/${timestamp}"
 
-              # Deploy to AWS
-              for stack_basename in $(find ../Output/${project}/${region_folder}/${environment}/Templates -name '*.yml' | sort --version-sort); do
-                stack_name=$(basename $stack_basename)
-                stack_name=${stack_name:4}
-                stack_name=${stack_name%.*}
+                  echo
+                  echo "Project:                ${project_hyphen_lower}"
+                  echo "Environment:            ${environment_lower}"
+                  echo "AWS Account:            ${aws_account_id}"
+                  echo "AWS Region:             ${region_hyphen}"
+                  echo "Template Bucket:        ${s3_bucket}/${s3_prefix}"
+                  echo
 
-                echo
-                echo "Assuming IAM Role"
-                iam_role="arn:aws:iam::${aws_account_id}:role/Administrator"
-                aws-google-auth -r ${iam_role}
+                  builder \
+                    --config      ./${project}/${region_folder}/BuildManifest.json \
+                    --path-output ../Output/${project}/${region_folder} \
+                    --environment ${environment}
+                  echo
 
-                echo
-                echo "Deploying: ${stack_basename}"
+                  # Deploy to AWS
+                  for stack_basename in $(find ../Output/${project}/${region_folder}/${environment}/Templates -name '*.yml' | sort --version-sort); do
+                    stack_name=$(basename $stack_basename)
+                    stack_name=${stack_name:4}
+                    stack_name=${stack_name%.*}
 
-                # Make sure the manual deployment bucket exists
+                    echo
+                    echo "Assuming IAM Role"
+                    iam_role="arn:aws:iam::${aws_account_id}:role/Administrator"
+                    aws-google-auth -r ${iam_role}
 
-                if aws s3 ls "s3://${s3_bucket}" --profile=sts 2>&1 | grep -q 'NoSuchBucket'; then
-                  echo "Creating template bucket: s3://${s3_bucket}"
-                  aws s3 mb "s3://${s3_bucket}" --profile=sts
+                    echo
+                    echo "Deploying: ${stack_basename}"
+
+                    # Make sure the manual deployment bucket exists
+
+                    if aws s3 ls "s3://${s3_bucket}" --profile=sts 2>&1 | grep -q 'NoSuchBucket'; then
+                      echo "Creating template bucket: s3://${s3_bucket}"
+                      aws s3 mb "s3://${s3_bucket}" --profile=sts
+                    fi
+
+                    if aws s3 ls "s3://${s3_bucket}" --profile=sts 2>&1 | grep -q 'NoSuchBucket'; then
+                      echo "ERROR: Could not create S3 bucket '${s3_bucket}'"
+                      exit 1;
+                    fi
+
+                    tag_filename=$(echo ${stack_basename} | sed 's/\/Templates\//\/Tags\//g' | sed 's/\.yml/\.json/g')
+
+
+                    # This is a load of crap- the AWS CLI craps out when a tag contains a space and is executed from a
+                    # shell script-- don't even ask, idea was stolen from here:
+                    # (https://stackoverflow.com/questions/59400050/how-do-you-add-spaces-for-aws-cli-cloudformation-deploy)
+
+                    deploy=(aws cloudformation deploy \
+                      --no-fail-on-empty-changeset \
+                      --profile sts \
+                      --stack-name "${stack_name}" \
+                      --template-file "${stack_basename}" \
+                      --s3-bucket "${s3_bucket}" \
+                      --s3-prefix "${s3_prefix}" \
+                      --capabilities "CAPABILITY_NAMED_IAM" \
+                      --region "${region_hyphen}" \
+                      --no-fail-on-empty-changeset \
+                      --tags $(cat ${tag_filename} | jq '.[] | (.Key + "=" + .Value)')
+                    )
+                    eval $(echo ${deploy[@]})
+
+                    error_code="${?}"
+                    if [[ "${error_code}" != "0" ]]; then
+                      echo "FATAL ERROR: AWS Deployment failed with error code ${error_code}";
+                      exit ${error_code};
+                    fi
+                    echo
+
+                  done
+
+                  echo "---------------------------------------------------------------------------------------------------------------"
                 fi
-
-                if aws s3 ls "s3://${s3_bucket}" --profile=sts 2>&1 | grep -q 'NoSuchBucket'; then
-                  echo "ERROR: Could not create S3 bucket '${s3_bucket}'"
-                  exit 1;
-                fi
-
-                tag_filename=$(echo ${stack_basename} | sed 's/\/Templates\//\/Tags\//g' | sed 's/\.yml/\.json/g')
-
-
-                # This is a load of crap- the AWS CLI craps out when a tag contains a space and is executed from a
-                # shell script-- don't even ask, idea was stolen from here:
-                # (https://stackoverflow.com/questions/59400050/how-do-you-add-spaces-for-aws-cli-cloudformation-deploy)
-
-                deploy=(aws cloudformation deploy \
-                  --no-fail-on-empty-changeset \
-                  --profile sts \
-                  --stack-name "${stack_name}" \
-                  --template-file "${stack_basename}" \
-                  --s3-bucket "${s3_bucket}" \
-                  --s3-prefix "${s3_prefix}" \
-                  --capabilities "CAPABILITY_NAMED_IAM" \
-                  --region "${region_hyphen}" \
-                  --tags $(cat ${tag_filename} | jq '.[] | (.Key + "=" + .Value)')
-                )
-                eval $(echo ${deploy[@]})
-
-                error_code="${?}"
-                if [[ "${error_code}" != "0" ]]; then
-                  echo "FATAL ERROR: AWS Deployment failed with error code ${error_code}";
-                  exit ${error_code};
-                fi
-                echo
-
-              done
-
-              echo
-              echo "---------------------------------------------------------------------------------------------------------------"
-            fi
+              fi
+            done
           fi
-        done
-      fi
+        fi
+      done
     done
 
   fi
 done
 
 echo
-
-
-
 
 
 
